### PR TITLE
UPSTREAM: 0000: Fix fuzzer for CertificateSigningRequest

### PR DESCRIPTION
**Pull request by mfojtik**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k @marun attempt to fix the roundtrip test with question about why we don't see this failing upstream :-)

**Comment by deads2k** [comment]
uh.... it doesn't look wrong, but it I don't see why its needed here and not upstream.

**Comment by mfojtik** [comment]
@deads2k it is failing here and no upstream, so I'm still confused why :-)

**Comment by marun** [comment]
Added to 166

**Pull request closed without merging**
